[project]
name = "tp-coo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.6",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
